# Generated by Django 3.1.1 on 2020-09-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftapp', '0002_auto_20200913_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoneritem',
            name='img',
            field=models.FilePathField(path='/home/mars/Workspace/Python/Loldraft.gg/draftapp/static/img/items'),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='id',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='img',
            field=models.FilePathField(path='/home/mars/Workspace/Python/Loldraft.gg/draftapp/static/img/spells'),
        ),
    ]
