# Generated by Django 3.1.1 on 2020-09-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftapp', '0004_auto_20200913_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='average_rank',
            field=models.CharField(choices=[('CHR', 'Challenger'), ('GMR', 'Grandmaster'), ('MR', 'Master'), ('DMD', 'Diamond'), ('PLAT', 'Platinum'), ('GLD', 'Gold'), ('SVR', 'Silver'), ('BRZ', 'Bronze'), ('IRON', 'Iron'), ('UNRK', 'Unranked')], max_length=4),
        ),
        migrations.AlterField(
            model_name='participant',
            name='rank',
            field=models.CharField(choices=[('CHR', 'Challenger'), ('GMR', 'Grandmaster'), ('MR', 'Master'), ('DMD', 'Diamond'), ('PLAT', 'Platinum'), ('GLD', 'Gold'), ('SVR', 'Silver'), ('BRZ', 'Bronze'), ('IRON', 'Iron'), ('UNRK', 'Unranked')], max_length=4),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='rank',
            field=models.CharField(choices=[('CHR', 'Challenger'), ('GMR', 'Grandmaster'), ('MR', 'Master'), ('DMD', 'Diamond'), ('PLAT', 'Platinum'), ('GLD', 'Gold'), ('SVR', 'Silver'), ('BRZ', 'Bronze'), ('IRON', 'Iron'), ('UNRK', 'Unranked')], max_length=4),
        ),
        migrations.AlterField(
            model_name='summonerrune',
            name='img',
            field=models.FilePathField(path='/home/mars/Workspace/Python/Loldraft.gg/draftapp/static/img/runes'),
        ),
    ]
