# Generated by Django 3.1.1 on 2020-09-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draftapp', '0005_auto_20200920_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='primary_rune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_rune', to='draftapp.summonerrune'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='secondary_rune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_rune', to='draftapp.summonerrune'),
        ),
    ]
